version: '3'

services:

  mysql-db:
    image: mysql:5.7
    container_name: mysql-btre
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: btredb
    ports:
      - "3306:3306"

  django-app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata seed.json &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    links:
      - mysql-db
    ports:
    - "8000:8000"
    depends_on: 
    - mysql-db



